services:
  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  back-end:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost:5001
  
  redis:
    image: redis