services:
  calculator:
    build: ./calculator
    ports:
      - 3000:3000
    container_name: calculator
  compute:
    build: ./compute
    environment:
      - VIRTUAL_HOST=compute.localtest.me
  load-balancer:
    build: ./load-balancer
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    container_name: load-balancer